version: "3.9"

services:
	node-app:
		container-name: devops-node-app-prod
		
		build:
			context: ./app
			dockerfile: Dockerfile

		ports:
		        -"3000:3000"

		volumes:
			-./data:/app/data

		env_file:
			- ./app/.env
