name: Node.js Docker CI/CD

on: 
  push: 
     branches: [main] 
     tags:
       - 'v*'
  workflow_dispatch:
    

jobs:
  build-and-push:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Debug ref info
         run: |
          echo "ref: $GITHUB_REF"
          echo "ref_name: $GITHUB_REF_NAME"
         

       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '18'

       - name: Install dependencies
         run: npm install
         working-directory: ./app

       - name: Run test
         run: npm test
         working-directory: ./app

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Extract version
         id: vars
         run:  echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
       

       - name: Build Docker image (branch)
         if: "!startsWith(github.ref, 'refs/tags/')"
         run: |
           docker build \
             -t ecesueryigit/dockerized-node-app:latest \
             -t ecesueryigit/dockerized-node-app:${{ github.sha }} \
             -t ecesueryigit/dockerized-node-app:${{ github.ref_name }} \
             ./app

       - name: Build Docker image (tag)
         if: "startsWith(github.ref, 'refs/tags/')"
         run: |
            docker build \
              -t ecesueryigit/dockerized-node-app:latest \
              -t ecesueryigit/dockerized-node-app:${{ github.sha }} \
              -t ecesueryigit/dockerized-node-app:${{ steps.vars.outputs.VERSION }} \
              ./app


       - name: Push Docker images (branch)
         if: "!startsWith(github.ref, 'refs/tags/')"
         run: |
           docker push ecesueryigit/dockerized-node-app:latest
           docker push ecesueryigit/dockerized-node-app:${{ github.sha }}
           docker push ecesueryigit/dockerized-node-app:${{ github.ref_name }}
           
       - name: Push Docker images (tag)
         if: "startsWith(github.ref, 'refs/tags/')"
         run: |
            docker push ecesueryigit/dockerized-node-app:latest
            docker push ecesueryigit/dockerized-node-app:${{ github.sha }}
            docker push ecesueryigit/dockerized-node-app:${{ steps.vars.outputs.VERSION }}

